export const LOGIN_CONSTANTS = {
    EMAIL_LABEL: "Email",
    EMAIL: "email",
    FORGOT_PASSWORD: "Forgot Password?",
    FORGOT_PASSWORD_URL: "../forgot-password",
    IRON_LOG_TITLE: "IronLog",
    LOGIN_BUTTON: "Login",
    PASSWORD_LABEL: "Password",
    PASSWORD: "password",
    EMAIL_PLACEHOLDER: "Enter your email address",
    PASSWORD_PLACEHOLDER: "Password",
    CREATE_ACCOUNT: "Create Account",
    SIGN_UP_URL: "../create-account",
    SIGN_IN: "Sign In",
    BACK_TO_LOGIN: "Back to Sign In",

};

export const CREATE_ACCOUNT_CONSTANTS = {
    PAGE_TITLE: "Create Your Account",
    PAGE_SUBTITLE: "Start tracking your strength journey",
    IRON_LOG_TITLE: "IronLog",
    FIRST_NAME_LABEL: "First Name",
    FIRST_NAME: "firstName",
    FIRST_NAME_PLACEHOLDER: "John",
    LAST_NAME_LABEL: "Last Name",
    LAST_NAME: "lastName",
    LAST_NAME_PLACEHOLDER: "Doe",
    USERNAME_LABEL: "Username",
    USERNAME: "username",
    USERNAME_PLACEHOLDER: "johndoe",
    EMAIL_LABEL: "Email",
    EMAIL: "email",
    EMAIL_PLACEHOLDER: "john@example.com",
    PASSWORD_LABEL: "Password",
    PASSWORD: "password",
    PASSWORD_PLACEHOLDER: "Create a strong password",
    CONFIRM_PASSWORD_LABEL: "Confirm Password",
    CONFIRM_PASSWORD: "confirmPassword",
    CONFIRM_PASSWORD_PLACEHOLDER: "Confirm your password",
    CREATE_BUTTON: "Create Account",
    ALREADY_HAVE_ACCOUNT: "Already have an account?",
    SIGN_IN_LINK: "Sign In",
    PASSWORD_HINT: "Must be at least 8 characters",
    HIDE_PASSWORD_ARIA: "Hide password",
    SHOW_PASSWORD_ARIA: "Show password",
    DISABLED_TOOLTIP: "Please fill out all fields correctly to proceed.",
};

export const FORGOT_PASSWORD_CONSTANTS = {
    PAGE_TITLE: "Reset Password",
    PAGE_SUBTITLE: "Enter your email and we'll send you a reset link",
    IRON_LOG_TITLE: "IronLog",
    EMAIL_LABEL: "Email Address",
    EMAIL: "email",
    EMAIL_PLACEHOLDER: "Enter your registered email",
    SUBMIT_BUTTON: "Send Reset Link",
    BACK_TO_LOGIN: "Back to Sign In",
    SUCCESS_TITLE: "Check your inbox",
    SUCCESS_MESSAGE: "If an account exists for that email, a password reset link has been sent.",
    RESEND_LABEL: "Didn't receive it?",
    RESEND_LINK: "Resend",
    DISABLED_TOOLTIP: "Please enter a valid email address.",
};